KeDynamicPartitioningSupported db ?     ; DATA XREF: KeQueryMaximumProcessorCountEx↑r
                                        ; sub_1403AFAE0+A↑r ...
dword_140CFC40C dd ?                    ; DATA XREF: sub_14038FFC4+6F↑r
                                        ; sub_14039040C↑r ...
; Exported entry 1909. PsProcessType
